"""
ZIP Exporter.
Bundles all generated test files for a given spec into a downloadable ZIP archive.
Includes a README and pytest.ini for immediate usability.
"""

import logging
import zipfile
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


class ZipExporter:
    """
    Creates a ZIP archive of all generated test files for a spec.
    The archive is structured for immediate `pytest` execution.
    """

    def __init__(self, generated_dir: Path):
        self.generated_dir = Path(generated_dir)

    def create_zip(self, spec_id: str) -> str:
        """
        Create a ZIP containing all test files for the given spec_id.
        Returns the absolute path to the created ZIP file.
        Raises FileNotFoundError if no test files are found.
        """
        # Gather test files: both spec-specific files AND conftest.py
        test_files = sorted(self.generated_dir.glob(f"{spec_id}_test_*.py"))
        conftest_file = self.generated_dir / "conftest.py"

        all_files = list(test_files)
        if conftest_file.exists():
            all_files.insert(0, conftest_file)

        if not all_files:
            raise FileNotFoundError(
                f"No generated test files found for spec_id '{spec_id}'. "
                "Please run test generation first."
            )

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        zip_filename = f"{spec_id}_tests_{timestamp}.zip"
        zip_path = self.generated_dir / zip_filename

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            # Add test files into a tests/ subdirectory within the ZIP
            for file_path in all_files:
                arcname = f"tests/{file_path.name}"
                zf.write(file_path, arcname=arcname)
                logger.debug(f"Added to ZIP: {arcname}")

            # Add pytest.ini for easy test execution
            zf.writestr("pytest.ini", self._generate_pytest_ini(spec_id))

            # Add requirements for the test suite
            zf.writestr("requirements-tests.txt", self._generate_test_requirements())

            # Add a README for the ZIP
            zf.writestr("README.md", self._generate_readme(spec_id, len(test_files)))

        logger.info(f"ZIP created: {zip_path} ({len(all_files)} files)")
        return str(zip_path)

    def _generate_pytest_ini(self, spec_id: str) -> str:
        """Generate a pytest.ini for the test bundle."""
        return f"""[pytest]
# Auto-generated pytest configuration for {spec_id} test suite
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --color=yes
markers =
    integration: Tests that require a live API server running
"""

    def _generate_test_requirements(self) -> str:
        """Generate requirements for running the test suite standalone."""
        return """# Requirements for running generated API tests
pytest>=7.4.0
requests>=2.31.0
pytest-html>=4.0.0
"""

    def _generate_readme(self, spec_id: str, test_file_count: int) -> str:
        """Generate a README.md for the ZIP bundle."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        return f"""# {spec_id} — Generated API Test Suite

Auto-generated by **AI-Powered API Test Generator**
Generated at: {timestamp}
Test files: {test_file_count}

## Quick Start

```bash
# 1. Install dependencies
pip install -r requirements-tests.txt

# 2. Set your API base URL (edit conftest.py or set env var)
export API_BASE_URL=http://your-api-host:port

# 3. Run all tests
pytest

# 4. Run with HTML report
pytest --html=report.html

# 5. Run only integration tests
pytest -m integration

# 6. Run a specific test file
pytest tests/test_<endpoint>.py -v
```

## Structure

```
.
├── tests/
│   ├── conftest.py          # Shared fixtures and configuration
│   └── {spec_id}_test_*.py  # One file per API endpoint
├── pytest.ini               # Pytest configuration
├── requirements-tests.txt   # Test dependencies
└── README.md                # This file
```

## Notes

- Tests use the `requests` library to make real HTTP calls
- Ensure the target API is running before executing tests
- Edit `BASE_URL` in each test file or `conftest.py` to point to your environment
- Tests include positive, negative, boundary, and status code validation cases
"""
